name: Test

on:
  pull_request:
  push:
    branches: main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22.12.0
          cache: "pnpm"

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build
        env:
          LLAMA_URL: "http://localhost:5001"
          CORE_DATABASE_URL: "http://localhost:4001"
          NEXT_PUBLIC_API_URL: "http://localhost:3001"
          NODE_ENV: "production"
          SMTP_HOST: localhost
          SMTP_PORT: 1025
          SMTP_USERNAME: mailhog
          SMTP_PASSWORD: mailhog

      - name: Lint
        run: pnpm lint

      - name: Test
        run: pnpm test
        env:
          LLAMA_URL: "http://localhost:5001"
          CORE_DATABASE_URL: "http://localhost:4001"
          NEXT_PUBLIC_API_URL: "http://localhost:3001"
          NODE_ENV: "production"
          SMTP_HOST: localhost
          SMTP_PORT: 1025
          SMTP_USERNAME: mailhog
          SMTP_PASSWORD: mailhog
